### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by sittingbool** [Siemienik/xlsx-import#1]
Hi, I am using a default typescript config. And its telling me that it does not find your module. How do you import it?
I am trying `import ImporterFactory from 'xlsx-import/ImporterFactory'` but I tried several other ways as well.

**Comment by sittingbool** [comment]
Found the error.
Your package json specifies a `"types": "lib/index.d.ts",` but there is no index.d.ts in your project

**Comment by sittingbool** [comment]
Workaround: specify path directly: `import ImporterFactory from 'xlsx-import/lib/ImporterFactory';`

**Comment by Siemienik** [comment]
@sittingbool Thank you for using this one and finding issue :)

**Comment by Siemienik** [comment]
resolved, now (in version 2.0.2) you can use `import ImporterFactory from 'xlsx-import'`

**Comment by Siemienik** [comment]
Hey, do you want to support my work? [**❤️ Sponsor me**](https://github.com/sponsors/Siemienik) 
Your issue is stuck? I can make it done, contact me for further info :)
