### ISSUE TITLE
[Q&A] How to handle multiple rows of headers?

### ISSUE THREAD

**Issue by fnick851** [Siemienik/xlsx-import#15]
Hi, how to read sheet with multiple rows of header? Is it possible at all? (For example, first row we have gender spanning two cells, second row we have male and female each in one cell, is it possible to preserve this data?) Thanks!

**Comment by Siemienik** [comment]
> Hi, how to read sheet with multiple rows of header? Is it possible at all? 
Yes it is by using `rowOffset: 2`

```js
```

**Comment by fnick851** [comment]
@Siemienik  Thanks. Are all cells parsed as string by default without a mapper?

**Comment by Siemienik** [comment]
> @Siemienik Thanks. Are all cells parsed as string by default without a mapper?

Default mapper is defined by code `(v: string) => v`.

Source code:
https://github.com/Siemienik/xlsx-import/blob/be72568ed68b1922c81731e45beecd89c3283ce9/src/Importer.ts#L22
and:
https://github.com/Siemienik/xlsx-import/blob/be72568ed68b1922c81731e45beecd89c3283ce9/src/Importer.ts#L41

**Comment by fnick851** [comment]
@Siemienik Thank you!

**Comment by Siemienik** [comment]
Hey, do you want to support my work? [**❤️ Sponsor me**](https://github.com/sponsors/Siemienik) 
Your issue is stuck? I can make it done, contact me for further info :)
