### ISSUE TITLE
[Q&A] What is the "index" variable?

### ISSUE THREAD

**Issue by fnick851** [Siemienik/xlsx-import#16]
Index: 5 for author, index: 2 for title - what do these do?

**Comment by Siemienik** [comment]
For type 'list' it is column index:

column A is indexed 1
column B is indexed 2
...
column E is indexed 5

**Comment by fnick851** [comment]
@Siemienik Thanks for the answer!

**Comment by Siemienik** [comment]
---
[_❤️ Sponsor me_](https://github.com/sponsors/Siemienik)
