### ISSUE TITLE
[REFACTORING] : introduce const MAPPER_DEFAULT 

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#18]
# Actual

Current default mapper is defined implicitly in two places: 
https://github.com/Siemienik/xlsx-import/blob/be72568ed68b1922c81731e45beecd89c3283ce9/src/Importer.ts#L22
https://github.com/Siemienik/xlsx-import/blob/be72568ed68b1922c81731e45beecd89c3283ce9/src/Importer.ts#L41

# Expected

The default mapper should be defined explicitly as a const `MAPPER_DEFAULT` (or some name like that)

**Comment by cmwalshWVU** [comment]
Hi I would like to work this issue for you.  Can I please have write access to this project to push my branch? Thank you

**Comment by Siemienik** [comment]
@cmwalshWVU 

> Hi I would like to work this issue for you. Can I please have write access to this project to push my branch? Thank you

Hi, I nice to hear that :) it is awesome, that some other peoples than me wants to contribute this project ❤️  

I can not give you write access, however you have a possibility to fork repo by the button on up&right display corner

![image](https://user-images.githubusercontent.com/2893099/94882159-8259d500-0467-11eb-95a9-47a134f0c399.png)

Then this repo should be clone on your profiles, with fully write access for you. (probably hosted as cmwalshWVU/xlsx-import). There It is recommend to commit changes into new branch.

Finally, when your fix is done and all commits pushed, please go to "Pull requests" and create new one targeting to this repo.

@lowkeypriority @cmwalshWVU Thank you again for contributing this library :)

If you want, I may create more well described issues here and on siemienik/xlsx-renderer labeled 'good first issue' . What do you think?

**Comment by lowkeypriority** [comment]
> Thank you again for contributing this library :
@Siemienik Thank you.

> If you want, I may create more well described issues here and on siemienik/xlsx-renderer labeled 'good first issue' 
It would be great if you could do this. This will make it easier to contribute and implement your ideas :)

**Comment by Siemienik** [comment]
I've create first one:
https://github.com/Siemienik/xlsx-import/issues/22
next I will add if only find some free time  :)
