### ISSUE TITLE
README formatting

### ISSUE THREAD

**Issue by lowkeypriority** [Siemienik/xlsx-import#26]
## Description

Formatting of current README is not good at all.

## Solving

I'm suggesting to format README with markdown rules from [markdownlint repo](https://github.com/DavidAnson/markdownlint/blob/v0.21.0/doc/Rules.md)

**Comment by Siemienik** [comment]
ok, that sounds fine:+1:

**Comment by Siemienik** [comment]
Close, because move into #61
