### ISSUE TITLE
[Refactoring] Rename variable

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#30]
# Actual

1. In:

https://github.com/Siemienik/xlsx-import/blob/0db404b6be0117f3f81ede01879b1bbed3a4a3d8/src/IImporter.ts#L4

and

https://github.com/Siemienik/xlsx-import/blob/0db404b6be0117f3f81ede01879b1bbed3a4a3d8/src/IImporter.ts#L11

a parameter is named `people` - It's wrong, should be named `config`

2. In:

https://github.com/Siemienik/xlsx-import/blob/0db404b6be0117f3f81ede01879b1bbed3a4a3d8/src/Importer.ts#L11

and

https://github.com/Siemienik/xlsx-import/blob/0db404b6be0117f3f81ede01879b1bbed3a4a3d8/src/Importer.ts#L24

a parameter is named just a `cfg` - I would prefer to use name `config`

# Expected

They should be named `config`

**Comment by Metastasis** [comment]
I would like to take this

**Comment by Siemienik** [comment]
@Metastasis it's your 👍 😄

**Comment by Metastasis** [comment]
Done
PR #35

**Comment by Siemienik** [comment]
@Metastasis thank you for quick development and the fixations which was done 😄
