### ISSUE TITLE
Insights / Contribution issue

### ISSUE THREAD

**Issue by Siemienik** [Siemienik/xlsx-import#51]
@Metastasis @Gontrum, both of You done a lot great works for this library but you aren appear on Contributor page... 😞

![image](https://user-images.githubusercontent.com/2893099/96336450-2c4c7a80-1080-11eb-83ce-b389f1def8dd.png)

I did a little research, I suppose that you have set different emails for commits than used in Github. To fix it please go to Settings/Emails ( https://github.com/settings/emails ) and add the following:  (I get these mails from git log)

@Metastasis `met*******@*****mail.ch`
@Gontrum `dav**.*******@*****vate.de`

After verification was done, GH will recalculate the Contributions page.

**Comment by Gontrum** [comment]
Hey @Siemienik,
 
thank you for catching that! I added the address I commited with :)

**Comment by Metastasis** [comment]
@Siemienik
done 👍

**Comment by Siemienik** [comment]
Great 🥇
