### ISSUE TITLE
Apply prettier to all directories

### ISSUE THREAD

**Issue by Metastasis** [Siemienik/xlsx-import#78]
I would like to propose adding other folders (such as samples and test folders) to [format script](https://github.com/Siemienik/xlsx-import/blob/master/package.json#L22)

Something like this
```json
{
  "format:code": "prettier --write \"**/*.{js,ts}\""
}
```

**Comment by Siemienik** [comment]
It is great idea, however we have to be sure do not format `node_modules` and `dist`. 

I've also created issue #64, where prettier will be replaced by eslint.
